[package]
name = "mosers"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = { version = "1", features = ["perf"] }
fancy-regex = "0"
lazy_static = "1"
strum = "0"
strum_macros = "0"

[dev-dependencies]
criterion = "0"

[[bench]]
name = "tokenizer_benchmark"
harness = false
