name: Rust

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.11
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy, llvm-tools-preview
          override: true

      - name: Install Grcov
        run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -

      # Necessary for now for the cargo cache: https://github.com/actions/cache/issues/133#issuecomment-599102035
      - if: matrix.os == 'ubuntu-latest'
        run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/

      - name: Install cargo-readme for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-readme

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --verbose --manifest-path ./mosers/Cargo.toml

      - name: Lint with RustFmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./mosers/Cargo.toml -- --check

      - name: Lint Benchmarks with RustFmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./mosers/Cargo.toml -- ./mosers/benches/tokenizer_benchmark.rs --check

      - name: Lint with Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./mosers/Cargo.toml --all-targets --all-features -- -D warnings

      - name: Run lib tests
        run: |
          export RUSTFLAGS="-Cinstrument-coverage"
          cargo build --verbose
          LLVM_PROFILE_FILE="shares-%p-%m.profraw" cargo test --verbose --manifest-path ./mosers/Cargo.toml --lib
          ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
          bash <(curl -s https://codecov.io/bash) -f lcov.info

      - name: Run doc Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --manifest-path ./mosers/Cargo.toml --doc

      # Verify that Readme.md is up to date.
      - name: Make sure, Readme generated from lib.rs matches actual Readme
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        working-directory: ./mosers
        run: cargo readme > must_match_readme.md && diff must_match_readme.md README.md
